paths:
  raw_data: data/raw/crash_locations.csv
  interim_dir: data/interim/
  processed_data: data/processed/final_dataset.csv
  images_dir: data/raw/images/

api_keys:
  google: YOUR_GOOGLE_API_KEY

params:
  buffer_radius: 500
  image_interval: 10